# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nconst', models.CharField(max_length=128)),
                ('primaryName', models.CharField(max_length=128)),
                ('birthYear', models.SmallIntegerField()),
                ('deathYear', models.SmallIntegerField()),
                ('primaryProfession', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=128)),
                ('titleType', models.CharField(max_length=128)),
                ('primaryTitle', models.CharField(max_length=128)),
                ('originalTitle', models.CharField(max_length=128)),
                ('isAdult', models.BooleanField(default=False)),
                ('startYear', models.SmallIntegerField()),
                ('endYear', models.SmallIntegerField()),
                ('runtimeMinutes', models.DurationField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None)),
            ],
        ),
        migrations.AddField(
            model_name='name',
            name='knownForTitles',
            field=models.ManyToManyField(to='api.Title'),
        ),
    ]
