# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171202_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='nconst',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='name',
            name='primaryName',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='name',
            name='primaryProfession',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='title',
            name='originalTitle',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='title',
            name='primaryTitle',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='title',
            name='tconst',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='title',
            name='titleType',
            field=models.CharField(max_length=1024),
        ),
    ]
