# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171202_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='birthYear',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='originalTitle',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
