# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171202_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(model_name='name', name='knownForTitles'),
        migrations.AddField(
            model_name='name',
            name='knownForTitles',
            field=models.ManyToManyField(through='api.KnownFor', to='api.Title'),
        ),
        migrations.AddField(
            model_name='knownfor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Name'),
        ),
        migrations.AddField(
            model_name='knownfor',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Title'),
        ),
    ]
