# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171202_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), db_index=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='title',
            name='startYear',
            field=models.SmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='tconst',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
